<?php

/**
 * @file
 * Manage Application Submission Module
 */
use Drupal\Component\Utility\Variable;
use Drupal\webform\Utility\WebformFormHelper;
use Drupal\Core\Render\Element;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\AlertCommand;
use Drupal\Core\Form\FormStateInterface;

use Drupal\application\Controller\ApplicationController;
use Drupal\application\Controller\SBALoanController;



function application_form_webform_submission_apply_for_ppp_loan_edit_all_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
    $elements = WebformFormHelper::flattenElements($form);
    #dpm($form["elements"]["request_document_1"]["1040_schedule_c"]);

    
}

function application_form_webform_submission_apply_for_ppp_loan_edit_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
    #$elements = WebformFormHelper::flattenElements($form);
    
    $form["elements"]["loan_officer_page"]["verified_net_earnings"]['#prefix'] = '<div id="loan-form-ajax-wrapper">';
    $form["elements"]["loan_officer_page"]["verified_net_earnings"]['#suffix'] = '</div>';
    
    $form["elements"]["loan_officer_page"]["sba_response"]["#prefix"] = '<div id="sba-response-ajax-wrapper">';
    $form["elements"]["loan_officer_page"]["sba_response"]["#suffix"] = "</div>";

    $form["elements"]["loan_officer_page"]["btn_verify"] = [
        '#type' => 'button',
        '#value' => t('Verify 1040 C'),
        '#ajax' => [
            'callback' => 'application_verify_net_earnings',
            'event' => 'click',
            'wrapper' => 'loan-form-ajax-wrapper',
            'progress' => [
                'type' => 'throbber',
                'message' => "Verifying",
            ],
        ]
    ];

    $form["elements"]["loan_officer_page"]["btn_send_to_sba"] = [
        '#type' => 'button',
        '#value' => t('Send to SBA'),
        '#ajax' => [
            'callback' => 'application_send_to_sba',
            'event' => 'click',
            'wrapper' => 'sba-response-ajax-wrapper',
            'progress' => [
                'type' => 'throbber',
                'message' => 'Sending...',
            ],
        ],
        '#weight' => 5,
    ];



}

function application_form_webform_submission_apply_for_ppp_loan_add_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
    $elements = WebformFormHelper::flattenElements($form);

    #dpm($elements);
    
    $elements["borrower_email"]["#default_value"] = \Drupal::currentUser()->getEmail();

    $application_controller = new ApplicationController($elements);

    $application_controller->login();

    $form['actions']['submit']['#submit'][]  = 'application_form_submit';


    

}

function application_form_submit(array &$form, FormStateInterface $form_state) {
    $elements = WebformFormHelper::flattenElements($form);
    $application_controller = new ApplicationController($elements);
    $application_controller->login();
    $application_controller->content();
}

function application_verify_net_earnings(array &$form, FormStateInterface $form_state) {
    #$response = new AjaxResponse();

    $elements = WebformFormHelper::flattenElements($form);

    $file_id = $form["elements"]["request_document_1"]["1040_schedule_c"]["#default_value"][0];
    
    if ($file_id) {
        $file = \Drupal\file\Entity\File::load($file_id);
        #$oNewFile->setPermanent();
        $filename = $file->getFilename();
    }

    $submission_id = $form["elements"]["request_document_1"]["1040_schedule_c"]["#webform_submission"];

    $full_filename = $submission_id . '/' . $filename;

    $client = \Drupal::httpClient();
    $request = $client->post('http://161.35.226.185:8000/detect_1040_schedule_C', [
        'form_params' => [
            'filename' => $full_filename,
        ],
        'headers' => [
            'Content-type' => 'application/x-www-form-urlencoded',
        ],
    ]);


    $result = json_decode($request->getBody());
    
    $form["elements"]["loan_officer_page"]["verified_net_earnings"]["#value"] = $result->{"response"};
    
    return $form["elements"]["loan_officer_page"]["verified_net_earnings"];
    
}

function application_send_to_sba(array &$form, FormStateInterface $form_state) {
    $elements = WebformFormHelper::flattenElements($form);
    $request_data_str = application_json_builder($elements);
    #dpm($request_data_str);
    $data = [
        'MethodNamePhysical' => 'Originate3',
        'CLSUsername' => 'isamuyun',
        'CLSPassword' => 'Squall39478',
        'CLSPIN' => '797415',
        'EMail' => 'yun@rmdslab.com',
        'FormatIn' => 'JSON',
        'RequestData' => $request_data_str,
        'SoftwareVendorCode' => "WZHZUDAQX",
	    'SoftwareVendorName' => "AMERICANLENDINGCENTER"
    ];

    $json_data = json_encode($data);
    
    $client = \Drupal::httpClient();
    $request = $client->post('https://catweb2.sba.gov/rest/elend/flexible/SharedEntryPoint', [
        'body' => $json_data,
        'headers' => [
            'Content-type' => 'application/json',
        ],
    ]);


    $result = json_decode($request->getBody());
    
    dpm(json_decode($result->ResponseData));
    
    $form["elements"]["loan_officer_page"]["sba_response"]["#value"] = $result->{"ResponseData"};



    return $form["elements"]["loan_officer_page"]["sba_response"];
}

function application_json_builder(array &$elements) {
    #dpm($elements);
    
    $request_data = new stdClass();
    $request_data->version = "6.0";
    

    $App = new stdClass();

    $LoanApplication = new stdClass();
    $LoanApplication->action = "insert";
    $LoanApplication->_comment = "test app #155585";
    $LoanApplication->AgentInvolved = "N";
    $LoanApplication->ProcessingMethodCd = "7AG";
    $App->LoanApplication = [$LoanApplication];
    
    $Borrower = new stdClass();
    $Borrower->action = "insert";
    $Borrower->TaxId = "0844669294";
    $Borrower->BusinessName = $elements["business_name"]["#default_value"];
    $Borrower->BusinessPersonInd = "B";
    $Borrower->BnkrptcyInd = "N";
    $Borrower->LastName = $elements["last_name"]["#default_value"];
    $App->Borrower = [$Borrower];
    
    $BusAppr = new stdClass();
    $BusAppr->action = "insert";
    $BusAppr->Ind = "ABV";
    $App->BusAppr = [$BusAppr];

    $ChangeOfOwnership = new stdClass();
    $ChangeOfOwnership->action = "insert";
    $ChangeOfOwnership->Loan7aPymtAmt = "1884000.00";
    $ChangeOfOwnership->TotalApprAmt = "1884000.00";
    $App->ChangeOfOwnership = [$ChangeOfOwnership];
    
    /*
    
    $App->Collateral = [];
    $CreditUnavailReasons = new stdClass();
    $CreditUnavailReasons->action = "insert";
    $CreditUnavailReasons->CreditUnavailReasonCd = "1";
    $CreditUnavailReasons->CreditUnavailReasonCommnt = "SIGNIFICANT COLLATERAL SHORTFALL";
    $App->CreditUnavailReasons = [$CreditUnavailReasons];
    
    $App->Eligibility = [];
    $App->Injection = [];
    $App->Interest = [];
    $App->PartnerInformation = [];
    $App->Principal = [];
    $App->PrincipalRace = [];
    $App->SpecialPurpose = [];
    $App->UseOfProceeds = [];
    */
    $request_data->App = [$App];

    #$request_data->App = [];

    return json_encode($request_data);
}