<?php

/**
 * @file
 * Manage Application Submission Module
 */
use Drupal\Component\Utility\Variable;
use Drupal\webform\Utility\WebformFormHelper;
use Drupal\Core\Render\Element;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\AlertCommand;
use Drupal\Core\Form\FormStateInterface;

use Drupal\application\Controller\ApplicationController;
use Drupal\application\Controller\SBALoanController;



function application_form_webform_submission_apply_for_ppp_loan_edit_all_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
    $elements = WebformFormHelper::flattenElements($form);

    application_verify_netearnings($form, $form_state);

    /*
    $imapPath = '{outlook.office365.com:993/imap/ssl}INBOX';
    $username = 'test@americanlendingcenter.com';
    $password = 'Welcome1';

    $inbox = imap_open($imapPath, $username, $password);
    // search and get unseen emails, function will return email ids
    $emails = imap_search($inbox, 'UNSEEN');

    $output = '';

    foreach ($emails as $mail) {
        $headerInfo = imap_headerinfo($inbox, $mail);

        $output .= $headerInfo->subject . '\n';
        $output .= $headerInfo->toaddress . '\n';
        $output .= $headerInfo->date . '\n';
        $output .= $headerInfo->fromaddress . '\n';
        $output .= $headerInfo->reply_toaddress . '\n';

        $emailStructure = imap_fetchstructure($inbox, $mail);
        if (!isset($emailStructure->parts)) {
            $output .= imap_body($inbox, $mail, FT_PEEK);
        }
        else {
            $output .= imap_body($inbox, $mail, FT_PEEK);
        }
    }
    dpm($output);
    // colse the connection
    imap_expunge($inbox);
    imap_close($inbox);
    */
}

function application_form_webform_submission_apply_for_ppp_loan_edit_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
    #$elements = WebformFormHelper::flattenElements($form);
    
    #$form["elements"]["loan_officer_page"]["verified_net_earnings"]['#prefix'] = '<div id="loan-form-ajax-wrapper">';
    #$form["elements"]["loan_officer_page"]["verified_net_earnings"]['#suffix'] = '</div>';
    
    $form["elements"]["loan_officer_page"]["sba_response"]["#prefix"] = '<div id="sba-response-ajax-wrapper">';
    $form["elements"]["loan_officer_page"]["sba_response"]["#suffix"] = "</div>";
    
    $form["elements"]["loan_officer_page"]["btn_cancel_loan"] = [
        '#type' => 'button',
        '#value' => t('Cancel Loan'),
        '#ajax' => [
            'callback' => 'application_cancel_loan',
            'event' => 'click',
            'wrapper' => 'sba-response-ajax-wrapper',
            'progress' => [
                'type' => 'throbber',
                'message' => "Verifying",
            ],
        ]
    ];

    $form["elements"]["loan_officer_page"]["btn_send_to_sba"] = [
        '#type' => 'button',
        '#value' => t('Send to SBA'),
        '#ajax' => [
            'callback' => 'application_send_to_sba',
            'event' => 'click',
            'wrapper' => 'sba-response-ajax-wrapper',
            'progress' => [
                'type' => 'throbber',
                'message' => 'Sending...',
            ],
        ],
        '#weight' => 5,
    ];

}

function application_form_webform_submission_apply_for_ppp_loan_add_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
    $elements = WebformFormHelper::flattenElements($form);

    #dpm($elements);
    
    #$elements["borrower_email"]["#default_value"] = \Drupal::currentUser()->getEmail();

    $elements["borrower_email"]["#default_value"] = "yun@rmdslab.com";

    $application_controller = new ApplicationController($elements);

    $application_controller->login();

    $form['actions']['submit']['#submit'][]  = 'application_form_submit';

    #$form['actions']['wizard_next']['#submit'][] = 'application_verify_netearnings';

    

}

function application_form_submit(array &$form, FormStateInterface $form_state) {
    $elements = WebformFormHelper::flattenElements($form);
    $application_controller = new ApplicationController($elements);
    $application_controller->login();
    $result = $application_controller->content();

    dpm($result);
}

function application_verify_netearnings(array &$form, FormStateInterface $form_state) {
    #$response = new AjaxResponse();

    $elements = WebformFormHelper::flattenElements($form);

    /*
    if (floatval($elements["verified_net_earnings"]["#default_value"]) > 0) {
        return;
    }

    $file_id = $form["elements"]["request_document_1"]["1040_schedule_c"]["#default_value"][0];
    
    if ($file_id) {
        $file = \Drupal\file\Entity\File::load($file_id);
        $filename = $file->getFilename();

        $submission_id = $form["elements"]["request_document_1"]["1040_schedule_c"]["#webform_submission"];

        $full_filename = $submission_id . '/' . $filename;
        
        $client = \Drupal::httpClient();
        $request = $client->post('http://161.35.226.185:8000/detect_1040_schedule_C', [
            'form_params' => [
                'filename' => $full_filename,
            ],
            'headers' => [
                'Content-type' => 'application/x-www-form-urlencoded',
            ],
        ]);
        

        $result = json_decode($request->getBody());
    
        $form["elements"]["loan_officer_page"]["verified_net_earnings"]["#value"] = $result->{"response"};
        $form["elements"]["loan_officer_page"]["verified_net_earnings"]["#default_value"] = $result->{"response"};
        $elements["verified_net_earnings"]["#default_value"] = $result->{"response"};
    }
    */
}

function application_cancel_loan(array &$form, FormStateInterface $form_state) {
    $elements = WebformFormHelper::flattenElements($form);
    $data = [
        'MethodNamePhysical' => 'Servicing2',
        'CLSUsername' => 'alctester',
        'CLSPassword' => 'Squall39478',
        'CLSPIN' => '303330',
        'EMail' => 'yun@rmdslab.com',
        'FormatIn' => 'XML',
        'FormatOut' => 'JSON',
        'RequestData' => "<SBA_ETran version=\"6.0\"><SBALoan action=\"cancel\"><Loan action=\"update\"><LoanApplicNmb>155878</LoanApplicNmb><LoanNmb>8936745005</LoanNmb></Loan></SBALoan></SBA_ETran>",
        'SoftwareVendorCode' => "WZHZUDAQX",
	    'SoftwareVendorName' => "AMERICANLENDINGCENTER"
    ];

    $json_data = json_encode($data);
    
    $client = \Drupal::httpClient();
    $request = $client->post('https://catweb2.sba.gov/rest/elend/flexible/SharedEntryPoint', [
        'body' => $json_data,
        'headers' => [
            'Content-type' => 'application/json',
        ],
    ]);


    $result = json_decode($request->getBody());
    
    dpm(json_decode($result->ResponseData));
    
    $form["elements"]["loan_officer_page"]["sba_response"]["#value"] = $result->{"ResponseData"};



    return $form["elements"]["loan_officer_page"]["sba_response"];
}

function application_send_to_sba(array &$form, FormStateInterface $form_state) {
    $elements = WebformFormHelper::flattenElements($form);
    $request_data_str = application_json_builder($elements);
    #dpm($request_data_str);
    $data = [
        'MethodNamePhysical' => 'Originate3',
        'CLSUsername' => 'alctester',
        'CLSPassword' => 'Squall39478',
        'CLSPIN' => '303330',
        'EMail' => 'yun@rmdslab.com',
        'FormatIn' => 'JSON',
        'RequestData' => $request_data_str,
        'SoftwareVendorCode' => "WZHZUDAQX",
	    'SoftwareVendorName' => "AMERICANLENDINGCENTER"
    ];

    $json_data = json_encode($data);
    
    $client = \Drupal::httpClient();
    $request = $client->post('https://catweb2.sba.gov/rest/elend/flexible/SharedEntryPoint', [
        'body' => $json_data,
        'headers' => [
            'Content-type' => 'application/json',
        ],
    ]);


    $result = json_decode($request->getBody());
    
    dpm(json_decode($result->ResponseData));
    
    $form["elements"]["loan_officer_page"]["sba_response"]["#value"] = $result->{"ResponseData"};



    return $form["elements"]["loan_officer_page"]["sba_response"];
}

function application_cancel_loan_builder(array &$elements) {
    $request_data = new stdClass();
    $request_data->version = "6.0";
    $App = new stdClass();
    $App->action = "cancel";
    $LoanApplication = new stdClass();
    $LoanApplication->action = "update";
    $LoanApplication->LoanApplicNmb = "155878";
    $LoanApplication->LoanNmb = "89367450-05";
    $App->LoanApplication = [$LoanApplication];
    $request_data->App = $App;
    return json_encode($request_data);
}

function application_json_builder(array &$elements) {
    #dpm($elements);
    
    $request_data = new stdClass();
    $request_data->version = "6.0";
    

    $App = new stdClass();

    $LoanApplication = new stdClass();
    $LoanApplication->action = "insert";
    $LoanApplication->_comment = "test app #155585";
    $LoanApplication->AgentInvolved = "N";
    $LoanApplication->BusinessAgeCd = "0";
    $LoanApplication->CollateralInd = "N";
    $LoanApplication->CurrEmpQty = "0";
    $LoanApplication->EligPassiveCompanyInd = "Y";
    $LoanApplication->FrnchiseInd = "N";
    $LoanApplication->FullAmortPymtInd = "Y";
    $LoanApplication->InjectionInd = "Y";
    $LoanApplication->InterestStructureCd = "V";
    $LoanApplication->JobsCreatdQty = "1";
    $LoanApplication->JobsRetaindQty = "3";
    $LoanApplication->LenderCntctEmail = "yun@rmdslab.com";
    $LoanApplication->LenderCntctFirstName = "John";
    $LoanApplication->LenderCntctLastName = "Shen";
    $LoanApplication->LenderCntctPhnNmb = "5624490139";
    $LoanApplication->LenderCntctTitl = "CEO";
    $LoanApplication->LifeInsurRqmtInd = "Y";
    $LoanApplication->LoanBusinessEstDt = "2020-02-11 00:00:00.0";
    $LoanApplication->LoanName = "Planet Express LLC";
    $LoanApplication->LoanTermMnths = "120";
    $LoanApplication->LoanTermStartTypInd = "N";
    $LoanApplication->MnthsIntrstOnlyQty = "0";
    $LoanApplication->NAICSCd = "812210";
    $LoanApplication->NoteDt = "2020-10-26 00:00:00.0";
    $LoanApplication->ProcessingMethodCd = "7AG";
    $LoanApplication->ProjectCityName = "Huntington";
    $LoanApplication->ProjectStCd = "IN";
    $LoanApplication->ProjectStrtName1 = "100 S Park Drive";
    $LoanApplication->ProjectStrtName2 = "";
    $LoanApplication->ProjectZip4Cd = "2633";
    $LoanApplication->ProjectZipCd = "46750";
    $LoanApplication->PymtAmt = "30000.00";
    $LoanApplication->PymtTypeCode = "F";
    $LoanApplication->ReconsiderationInd = "N";
    $LoanApplication->RequestedAmt = "240000.00";
    $LoanApplication->RuralUrbanInd = "R";
    $LoanApplication->SBAGntyPct = "75.000";
    $LoanApplication->UnderwritingBy = "SBA";
    $App->LoanApplication = [$LoanApplication];
    
    $Borrower = new stdClass();
    $Borrower->action = "insert";
    $Borrower->TaxId = "0844669294";
    $Borrower->BusinessPersonInd = "B";
    $Borrower->BnkrptcyInd = "N";
    $Borrower->BooksToLenderWithinDays = "180";
    $Borrower->BusDUNSNmb = "069752764";
    $Borrower->BusinessName = $elements["business_name"]["#default_value"];
    $Borrower->BusOutstandingDebtInd = "N";
    $Borrower->BusPrimCntctNm = "Donald D Duck";
    $Borrower->ControlInterestType = "9";
    $Borrower->CurrOwnrshpEstblshDt = "Feb 11 2020 12:00AM";
    $Borrower->EPCOperatingCompnyCd = "3";
    $Borrower->ExtrnlCreditScorInd = "N";
    $Borrower->FedDisqualifiedInd = "N";
    $Borrower->GamblingOrSexualNatureInd = "N";
    $Borrower->InsurLiabInd = "Y";
    $Borrower->InsurLiabProductInd = "Y";
    $Borrower->InsurLiquorInd = "N";
    $Borrower->InsurMalpracticeInd = "N";
    $Borrower->InsurOtherInd = "N";
    $Borrower->InsurWorkersCompInd = "Y";
    $Borrower->LawsuitInd = "N";
    $Borrower->LegalOrgnztnCd = "4";
    $Borrower->MailCityName = "Huntington";
    $Borrower->MailCountryCd = "US";
    $Borrower->MailStCd = "IN";
    $Borrower->MailStrtName1 = "100 S Park Drive";
    $Borrower->MailStrtName2 = "";
    $Borrower->MailZip4Cd = "";
    $Borrower->MailZipCd = "46750";
    $Borrower->NonFedEmpInd = "Y";
    $Borrower->NonFmrSBAEmpInd = "Y";
    $Borrower->NonGS13EmpInd = "Y";
    $Borrower->NonLegBrnchEmpInd = "Y";
    $Borrower->NonSBACEmpInd = "Y";
    $Borrower->PaymentsLessThanCCInd = "";
    $Borrower->PhysCityName = "Huntington";
    $Borrower->PhysCountryCd = "US";
    $Borrower->PhysPostalCd = "";
    $Borrower->PhysStCd = "IN";
    $Borrower->PhysStrtName1 = "100 S Park Drive";
    $Borrower->PhysStrtName2 = "";
    $Borrower->PhysZip4Cd = "";
    $Borrower->PhysZipCd = "46750";
    $Borrower->PrevGovFinInd = "N";
    $Borrower->PrimaryBusinessInd = "Y";
    $Borrower->PrimaryPhone = "3013561710";
    $Borrower->PriorSBALoanInd = "N";
    $Borrower->LastName = $elements["last_name"]["#default_value"];

    $Borrower2 = new stdClass();
    $Borrower2->action = "insert";
    $Borrower2->TaxId = "0844692533";
    $Borrower2->BusinessPersonInd = "B";
    $Borrower2->BnkrptcyInd = "N";
    $Borrower2->BooksToLenderType = "12";
    $Borrower2->BooksToLenderWithinDays = "180";
    $Borrower2->BusinessName = "GHQ Realty LLC";
    $Borrower2->BusOutstandingDebtInd = "N";
    $Borrower2->BusPrimCntctNm = "Donald D Duck";
    $Borrower2->ControlInterestType = "7";
    $Borrower2->CurrOwnrshpEstblshDt = "Feb 12 2020 12:00AM";
    $Borrower2->EPCOperatingCompnyCd = "2";
    $Borrower2->ExtrnlCreditScorInd = "N";
    $Borrower2->FedDisqualifiedInd = "N";
    $Borrower2->GamblingOrSexualNatureInd = "N";
    $Borrower2->LawsuitInd = "N";
    $Borrower2->LegalOrgnztnCd = "4";
    $Borrower2->NonFedEmpInd = "Y";
    $Borrower2->NonFmrSBAEmpInd = "Y";
    $Borrower2->NonGS13EmpInd = "Y";
    $Borrower2->NonLegBrnchEmpInd = "Y";
    $Borrower2->NonSBACEmpInd = "Y";
    $Borrower2->PhysCityName = "Huntington";
    $Borrower2->PhysCountryCd = "US";
    $Borrower2->PhysStCd = "IN";
    $Borrower2->PhysStrtName1 = "100 S Park Drive";
    $Borrower2->PhysStrtName2 = "";
    $Borrower2->PhysZip4Cd = "";
    $Borrower2->PhysZipCd = "46750";
    $Borrower2->PrevGovFinInd = "N";
    $Borrower2->PrimaryBusinessInd = "N";
    $Borrower2->PrimaryPhone = "3013561710";
    $Borrower2->PriorSBALoanInd = "N";
    $App->Borrower = [$Borrower, $Borrower2];
    
    $BusAppr = new stdClass();
    $BusAppr->action = "insert";
    $BusAppr->Ind = "ABV";
    $App->BusAppr = [$BusAppr];

    $ChangeOfOwnership = new stdClass();
    $ChangeOfOwnership->action = "insert";
    $ChangeOfOwnership->BuyerEqtyBorrAmt = "0.00";
    $ChangeOfOwnership->BuyerEqtyCashAmt = "0.00";
    $ChangeOfOwnership->BuyerEqtyOthAmt = "0.00";
    $ChangeOfOwnership->Loan7aPymtAmt = "1946100.00";
    $ChangeOfOwnership->SellerFinanFullStbyAmt = "0.00";
    $ChangeOfOwnership->SellerFinanNonFullStbyAmt = "0.00";
    #$ChangeOfOwnership->TotalApprAmt = "1884000.00";
    $App->ChangeOfOwnership = [$ChangeOfOwnership];
    
    $App->Collateral = [];
    
    $CreditUnavailReasons = new stdClass();
    $CreditUnavailReasons->action = "insert";
    $CreditUnavailReasons->CreditUnavailReasonCd = "1";
    $CreditUnavailReasons->CreditUnavailReasonCommnt = "SIGNIFICANT COLLATERAL SHORTFALL";
    $App->CreditUnavailReasons = [$CreditUnavailReasons];
    
    $Eligibility = new stdClass();
    $Eligibility->action = "insert";
    $Eligibility->EligibleCd = "102";
    $Eligibility->EligibleInd = "Y";
    $App->Eligibility = [$Eligibility];

    $Injection = new stdClass();
    $Injection->action = "insert";
    $Injection->InjctnAmt = "108000.00";
    $Injection->InjctnOthDescTxt = "Down payment on purchase";
    $Injection->InjctnTermNotLessThanYrNmb = "";
    $Injection->InjctnTypCd = "C";
    $App->Injection = [$Injection];
    
    $Interest = new stdClass();
    $Interest->action = "insert";
    $Interest->Phase = "1";
    $Interest->AdjustPeriodCd = "Q";
    $Interest->AdjustPeriodMnths = "";
    $Interest->BaseIntrstRatePct = "4.75000";
    $Interest->BaseRateSourcTypCd = "WSJ";
    $Interest->BorrIntrstRatePct = "5.75000";
    $Interest->FirstRateAdjustDt = "2020-11-01 00:00:00.0";
    $Interest->IntrstGuaranteeInd = "F";
    $Interest->IntrstTypInd = "V";
    $Interest->ShareOfTotalMnths = "120";
    $Interest->ShareOfTotalPct = "100.000";
    $App->Interest = [$Interest];
    
    $PartnerInformation = new stdClass();
    $PartnerInformation->action = "insert";
    $PartnerInformation->LocationId = "507148";
    $App->PartnerInformation = [$PartnerInformation];
    
    $Principal = new stdClass();
    $Principal->action = "insert";
    $Principal->BusinessTaxId = "0844669294";
    $Principal->TaxId = "1306849681";
    $Principal->BusinessPersonInd = "P";
    $Principal->BirthCityName = "Wabash";
    $Principal->BirthCntryName = "USA";
    $Principal->BirthDt = "Apr 11 1980 12:00AM";
    $Principal->BirthStCd = "IN";
    $Principal->BnkrptcyInd = "N";
    $Principal->ControlInterestType = "7";
    $Principal->CreditScorSourcCd = "14";
    $Principal->EthnicCd = "HN";
    $Principal->ExtrnlCreditScorDt = "Jan 21 2020 12:00AM";
    $Principal->ExtrnlCreditScorInd = "Y";
    $Principal->ExtrnlCreditScorNmb = "790";
    $Principal->FirstName = "Donald";
    $Principal->GndrCd = "M";
    $Principal->GntyInd = "Y";
    $Principal->GntyTypCd = "1";
    $Principal->InsuranceAmt = "1100000.00";
    $Principal->InsuranceDisabInd = "N";
    $Principal->InsuranceLifeInd = "Y";
    $Principal->LastName = "Duck";
    $Principal->LawsuitInd = "N";
    $Principal->LglActnInd = "N";
    $Principal->MiddleInitial = "D";
    $Principal->NoNCAInd = "N";
    $Principal->OwnrshpInBusinessPct = "90.00";
    $Principal->PhysCityName = "Huntington";
    $Principal->PhysCountryCd = "US";
    $Principal->PhysStCd = "IN";
    $Principal->PhysStrtName1 = "142 Folk Street";
    $Principal->PhysStrtName2 = "";
    $Principal->PhysZip4Cd = "";
    $Principal->PhysZipCd = "46750";
    $Principal->Title = "Manager";
    $Principal->USCitznInd = "US";
    $Principal->VetCd = "1";
    $Principal->VetCertInd = "N";
    $App->Principal = [$Principal];

    $PrincipalRace = new stdClass();
    $PrincipalRace->action = "insert";
    $PrincipalRace->TaxId = "1306849681";
    $PrincipalRace->BusinessPersonInd = "P";
    $PrincipalRace->RaceCd = "7";

    $App->PrincipalRace = [$PrincipalRace];

    $SpecialPurpose = new stdClass();
    $SpecialPurpose->action = "insert";
    $SpecialPurpose->SpcPurpsLoanCd = "NOSP";
    $App->SpecialPurpose = [$SpecialPurpose];
    
    $UseOfProceeds = new stdClass();
    $UseOfProceeds->action = "insert";
    $UseOfProceeds->ProceedTypCd = "A";
    $UseOfProceeds->LoanProceedTypCd = "16";
    $UseOfProceeds->ProceedAmt = "1946100.00";
    $UseOfProceeds->PurchaseAgrmtNCAInd = "Y";
    $UseOfProceeds->PurchaseIntngblAssetAmt = "1800000.00";
    $UseOfProceeds->RefDescTxt = "Handy Example";
    
    $App->UseOfProceeds = [$UseOfProceeds];
    $request_data->App = [$App];

    return json_encode($request_data);
}

function application_form_webform_submission_forgiveness_form_add_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
    $elements = WebformFormHelper::flattenElements($form);

    #$elements["borrower_email"]["#default_value"] = \Drupal::currentUser()->getEmail();

    $elements["borrower_email"]["#default_value"] = "yunforreg@gmail.com";

    $application_controller = new ApplicationController($elements);

    $application_controller->login();

    #$form['actions']['submit']['#submit'][]  = 'application_forgiveness_form_submit';

    #$form['actions']['wizard_next']['#submit'][] = 'application_verify_netearnings';

    
    $form["elements"]["envelope_id"]["#prefix"] = '<div id="envelope-id-ajax-wrapper">';
    $form["elements"]["envelope_id"]["#suffix"] = "</div>";
    
    $form["elements"]["btn_create_envelope"] = [
        '#type' => 'button',
        '#value' => t('Create Envelope'),
        '#ajax' => [
            'callback' => 'application_create_envelope',
            'event' => 'click',
            'wrapper' => 'envelope-id-ajax-wrapper',
            'progress' => [
                'type' => 'throbber',
                'message' => "Verifying",
            ],
        ]
    ];
    
    $form["elements"]["document_name"]["#prefix"] = '<div id="document-name-ajax-wrapper">';
    $form["elements"]["document_name"]["#suffix"] = '</div>';

    $form["elements"]["btn_download_document"] = [
        '#type' => 'button',
        '#value' => t('Download Document'),
        '#ajax' => [
            'callback' => 'application_download_document',
            'event' => 'click',
            'wrapper' => 'document-name-ajax-wrapper',
            'progress' => [
                'type' => 'throbber',
                'message' => "Verifying",
            ],
        ]
    ];

}

function application_create_envelope(array &$form, FormStateInterface $form_state) {
    $elements = WebformFormHelper::flattenElements($form);
    
    $application_controller = new ApplicationController($elements);
    $application_controller->login();
    $result = $application_controller->buildForgivenessForm();

    $form["elements"]["envelope_id"]["#value"] = $result["envelope_id"];
    $form["elements"]["envelope_id"]["#default_value"] = $result["envelope_id"];
    
    return $form["elements"]["envelope_id"];
}

function application_forgiveness_form_submit(array &$form, FormStateInterface $form_state) {
    $elements = WebformFormHelper::flattenElements($form);
    $application_controller = new ApplicationController($elements);
    $application_controller->login();
    #$result = $application_controller->buildForgivenessForm();

    
    #$elements["envelope_id"]["#default_value"] = $result["envelope_id"];
    
    #$entity = $form_state->getFormObject()->getEntity();
    #$data = $entity->getData();
    #$data["envelope_id"] = $result["envelope_id"];
    #$entity->setData($data);
    #$entity["#data"]["envelope_id"] = $result["envelope_id"];
    #$entity->save();

    $results = $application_controller->downloadForgivenessForm();
}

function application_download_document(array &$form, FormStateInterface $form_state) {
    $elements = WebformFormHelper::flattenElements($form);
    
    $application_controller = new ApplicationController($elements);
    $application_controller->login();
    $results = $application_controller->downloadForgivenessForm();

    $form["elements"]["document_name"]["#value"] = $results;
    $form["elements"]["document_name"]["#default_value"] = $results;
    
    return $form["elements"]["document_name"];
}